<script>
  import Schedule from './Schedule.svelte';
  import Standings from './Standings.svelte';
  import Playoffs from './Playoffs.svelte';
  import Lightbox from './Lightbox.svelte';

  let tournament = $state(null);
  let photoMap = $state({});
  let currentTab = $state('schedule');
  let lightboxSrc = $state(null);

  const tabs = [
    { id: 'schedule', label: 'Games', icon: 'calendar' },
    { id: 'standings', label: 'Standings', icon: 'trophy' },
    { id: 'playoffs', label: 'Playoffs', icon: 'bracket' },
  ];

  const base = import.meta.env.BASE_URL;

  async function load() {
    const [tournamentRes, photosRes] = await Promise.all([
      fetch(`${base}tournament.json`),
      fetch(`${base}photos.json`).catch(() => null),
    ]);
    tournament = await tournamentRes.json();

    // photos.json maps game IDs to file paths (generated by scripts/gen-photos.sh)
    if (photosRes?.ok) {
      const raw = await photosRes.json();
      const map = {};
      for (const [id, path] of Object.entries(raw)) {
        map[id] = `${base}${path}`;
      }
      photoMap = map;
    }
  }

  function openPhoto(gameId) {
    lightboxSrc = photoMap[gameId] || null;
  }

  let played = $derived(tournament ? tournament.regularSeason.filter(g => g.score1 !== null).length : 0);
  let total = $derived(tournament ? tournament.regularSeason.length : 0);

  load();
</script>

<div class="shell">
  <header class="header">
    <div class="header-inner">
      <div class="brand">
        <div class="logo-mark">
          <svg width="26" height="26" viewBox="0 0 40 40" fill="none">
            <circle cx="20" cy="20" r="18" stroke="var(--accent)" stroke-width="2.5"/>
            <path d="M20 2 L20 38" stroke="var(--accent)" stroke-width="1.2" opacity="0.35"/>
            <path d="M2 20 L38 20" stroke="var(--accent)" stroke-width="1.2" opacity="0.35"/>
            <path d="M20 8 C26 8, 32 14, 32 20" stroke="var(--accent)" stroke-width="1.5" opacity="0.5"/>
            <path d="M20 32 C14 32, 8 26, 8 20" stroke="var(--accent)" stroke-width="1.5" opacity="0.5"/>
          </svg>
        </div>
        {#if tournament}
          <div>
            <h1 class="title">{tournament.name}</h1>
            <p class="meta">{played}/{total} games played</p>
          </div>
        {/if}
      </div>

      <!-- Desktop tabs in header -->
      <nav class="desktop-nav">
        {#each tabs as tab}
          <button
            class="desktop-tab"
            class:active={currentTab === tab.id}
            onclick={() => currentTab = tab.id}
            type="button"
          >
            {tab.label}
          </button>
        {/each}
      </nav>
    </div>
  </header>

  <main class="content">
    {#if tournament}
      {#if currentTab === 'schedule'}
        <Schedule games={tournament.regularSeason} teams={tournament.teams} {photoMap} {openPhoto} />
      {:else if currentTab === 'standings'}
        <Standings games={tournament.regularSeason} teams={tournament.teams} />
      {:else if currentTab === 'playoffs'}
        <Playoffs games={tournament.playoffs} teams={tournament.teams} {photoMap} {openPhoto} />
      {/if}
    {/if}
  </main>

  <!-- Mobile bottom nav -->
  <nav class="bottom-nav">
    {#each tabs as tab}
      <button
        class="nav-btn"
        class:active={currentTab === tab.id}
        onclick={() => currentTab = tab.id}
        type="button"
      >
        <div class="nav-icon-wrap">
          <svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            {#if tab.icon === 'calendar'}
              <rect x="3" y="4" width="18" height="18" rx="2"/>
              <line x1="3" y1="10" x2="21" y2="10"/>
              <line x1="9" y1="2" x2="9" y2="6"/>
              <line x1="15" y1="2" x2="15" y2="6"/>
            {:else if tab.icon === 'trophy'}
              <path d="M6 9H4a2 2 0 01-2-2V5h4"/>
              <path d="M18 9h2a2 2 0 002-2V5h-4"/>
              <path d="M4 5h16v4a6 6 0 01-6 6h-4a6 6 0 01-6-6V5z"/>
              <path d="M12 15v3"/>
              <path d="M8 21h8"/>
              <path d="M8 18h8"/>
            {:else if tab.icon === 'bracket'}
              <path d="M4 4v6a2 2 0 002 2h2"/>
              <path d="M4 20v-6a2 2 0 012-2h2"/>
              <path d="M20 4v6a2 2 0 01-2 2h-2"/>
              <path d="M20 20v-6a2 2 0 00-2-2h-2"/>
              <line x1="8" y1="12" x2="16" y2="12"/>
            {/if}
          </svg>
        </div>
        <span class="nav-label">{tab.label}</span>
      </button>
    {/each}
  </nav>
</div>

<Lightbox src={lightboxSrc} onclose={() => lightboxSrc = null} />

<style>
  .shell {
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
    background: var(--bg);
  }

  /* --- Header --- */
  .header {
    flex-shrink: 0;
    background: var(--surface);
    padding: 0.875rem 1.25rem;
    padding-top: max(0.875rem, env(safe-area-inset-top));
    box-shadow: var(--shadow-sm);
    position: relative;
    z-index: 5;
  }

  .header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .brand {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .logo-mark {
    width: 2.5rem;
    height: 2.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--accent-light);
    border-radius: 0.75rem;
    flex-shrink: 0;
  }

  .title {
    font-family: var(--font-display);
    font-size: 1rem;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.01em;
    line-height: 1.15;
    color: var(--text);
  }

  .meta {
    font-size: 0.7rem;
    font-weight: 500;
    color: var(--text-muted);
    margin-top: 0.1rem;
  }

  /* Desktop nav — hidden on mobile */
  .desktop-nav {
    display: none;
    gap: 0.25rem;
    padding: 0.2rem;
    background: var(--surface2);
    border-radius: var(--radius-sm);
  }

  .desktop-tab {
    padding: 0.5rem 1.25rem;
    border: none;
    border-radius: 0.5rem;
    background: transparent;
    font-family: var(--font-body);
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--text-muted);
    cursor: pointer;
    transition: all 0.2s;
  }

  .desktop-tab:hover {
    color: var(--text-secondary);
  }

  .desktop-tab.active {
    background: var(--surface);
    color: var(--accent);
    box-shadow: var(--shadow-sm);
  }

  /* --- Content --- */
  .content {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
    -webkit-overflow-scrolling: touch;
  }

  /* --- Mobile bottom nav --- */
  .bottom-nav {
    flex-shrink: 0;
    display: flex;
    background: var(--surface);
    box-shadow: 0 -2px 10px rgba(0,0,0,0.05);
    padding-bottom: var(--safe-bottom);
    position: relative;
    z-index: 5;
  }

  .nav-btn {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.15rem;
    padding: 0.5rem 0 0.4rem;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    transition: color 0.2s;
  }

  .nav-icon-wrap {
    width: 2rem;
    height: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 0.5rem;
    transition: background 0.2s;
  }

  .nav-btn.active .nav-icon-wrap {
    background: var(--accent-light);
  }

  .nav-btn.active {
    color: var(--accent);
  }

  .nav-icon {
    width: 20px;
    height: 20px;
  }

  .nav-label {
    font-size: 0.6rem;
    font-weight: 700;
    letter-spacing: 0.02em;
  }

  /* --- Desktop --- */
  @media (min-width: 768px) {
    .header {
      padding: 0.875rem 2.5rem;
      border-bottom: 1px solid var(--border);
      box-shadow: none;
    }

    .header-inner {
      max-width: 72rem;
      margin: 0 auto;
    }

    .desktop-nav {
      display: flex;
    }

    .bottom-nav {
      display: none;
    }
  }
</style>
